### ISSUE TITLE
Installation of Python Wrapper

### ISSUE THREAD

**Issue by sehepp** [KijinKims/VirPipe#4]
Hello,
I am trying to install virpipe. So far I am able to successfully install everything up until the point where I try to install the python wrapper. 

I run conda create -n virpipe -c skkujin virpipe -v and get the following:

_Collecting package metadata (current_repodata.json): ...working... INFO conda.gateways.repodata:conda_http_errors(203): Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/skkujin/linux-64/current_repodata.json
done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          
Traceback (most recent call last):
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1132, in __call__
    return func(*args, **kwargs)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 69, in main_subshell
    exit_code = do_call(args, p)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/notices/core.py", line 121, in wrapper
    return func(*args, **kwargs)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/cli/install.py", line 309, in install
    raise e
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/cli/install.py", line 264, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 177, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 301, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 84, in decorated
    return f(*args, **kwds)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 851, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 84, in decorated
    return f(*args, **kwds)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 1324, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/home/zvbd/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 350, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError_

I am very new to all of this, what would you suggest trying?

**Comment by rkkims** [comment]
Hi Sehepp,

Thank you for bringing this error to my attention.

I've discovered that the issue arises from not having the required conda channels installed for the virpipe installation.

Please install bioconda using the following commands:

```console
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```

Afterwards, please try the same command again.

Best,
Kijin
